[package]
name = "steamsync-tauri"
version = "0.1.0"
description = "Tauri GUI for steamsync"
license = "AGPL-3.0-or-later"
edition = "2021"

[lib]
name = "steamsync_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
